blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.TopicList.as_view(), name="topics"),
    path("<slug:slug>/", views.TopicDetail.as_view(), name="topic_detail"),
]

blog/models.py
from django.db import models

# Create your models here.
STATUS = ((0, "Draft"), (1, "Publish"))


class Topic(models.Model):
    """
    Define the data fields for a blog topic
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Topic


# Create your views here.
class TopicList(generic.ListView):
    """
    A view to render a list of blog topics
    """
    queryset = Topic.objects.filter(status=1).order_by("-created_on")
    template_name = "blog/topics.html"


class TopicDetail(generic.DetailView):
    """
    A view to provide a detail view of the full blog entry
    """
    model = Topic
    template_name = "blog/topic_detail.html"

blog/templates/blog/topic_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<div class="container">
   <div class="row g-0">
      <div class="col card mb-4 mt-3 top">
         <div class="card-body">
            <h1>{{ topic.title }}</h1>
            <p class=" text-muted">{{ topic.created_on }}</p>
            <p class="card-text ">{{ topic.content | safe }}</p>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

blog/templates/blog/topics.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" id="blog">
   <div class="row g-0">
      <div class="col text-center">
         <hr>
         <h2>Trending Topics</h2>
         <p>Check Out The Latest Trending Topics In The Clean Beauty Industry</p>
         <hr>
      </div>
   </div>
</div>
<div class="container">
   <div class="row g-0">
      <!-- Topic Column -->
      <div class="col">
         {% for topic in topic_list %}
         <div class="card mb-4">
            <div class="card-body">
               <h2 class="card-title">{{ topic.title }}</h2>
               <p class="card-text text-muted h6">{{ topic.created_on}} </p>
               <p class="card-text">{{topic.content|slice:":200" }}</p>
               <a href="{% url 'topic_detail' topic.slug  %}" class="btn btn-primary">Read More &rarr;</a>
            </div>
         </div>
         {% endfor %}
      </div>
   </div>
</div>
{% endblock %}